-- layouts/base.lua
-- Full page shell. Replaces layouts/base.jet.
-- Called as: base(data, content) -> string
-- data: Go handler map; content: pre-rendered body HTML string.

local nav = require("partials.nav")
local toast = require("partials.toast")

return function(data, content)
	return table.concat({
		"<!DOCTYPE html>",
		'<html lang="en" class="h-full">',
		"<head>",
		'    <meta charset="utf-8">',
		'    <meta name="viewport" content="width=device-width, initial-scale=1">',
		"    <title>goIsekai</title>",
		'    <link rel="icon" type="image/svg+xml" href="/static/favicon.svg">',
		'    <link rel="stylesheet" href="/static/lib/tailwind.css">',
		"    <style>",
		"        html { font-size: 17.5px; }",
		"        :where(a, button, input, select, textarea, summary):focus-visible {",
		"            outline: 2px solid #6366f1;",
		"            outline-offset: 2px;",
		"            border-radius: 4px;",
		"        }",
		"        a, button, input, select, textarea {",
		"            transition: color .15s, background-color .15s, border-color .15s;",
		"        }",
		"        @font-face {",
		"            font-family: 'Space Grotesk';",
		"            font-style: normal;",
		"            font-weight: 400;",
		"            font-display: swap;",
		"            src: url('/static/lib/fonts/space-grotesk-latin-400-normal.woff2') format('woff2');",
		"        }",
		"        @font-face {",
		"            font-family: 'Space Grotesk';",
		"            font-style: normal;",
		"            font-weight: 500;",
		"            font-display: swap;",
		"            src: url('/static/lib/fonts/space-grotesk-latin-500-normal.woff2') format('woff2');",
		"        }",
		"        @font-face {",
		"            font-family: 'Space Grotesk';",
		"            font-style: normal;",
		"            font-weight: 600;",
		"            font-display: swap;",
		"            src: url('/static/lib/fonts/space-grotesk-latin-600-normal.woff2') format('woff2');",
		"        }",
		"        @font-face {",
		"            font-family: 'Space Grotesk';",
		"            font-style: normal;",
		"            font-weight: 700;",
		"            font-display: swap;",
		"            src: url('/static/lib/fonts/space-grotesk-latin-700-normal.woff2') format('woff2');",
		"        }",
		"        h1, h2, h3 {",
		"            font-family: 'Space Grotesk', system-ui, sans-serif;",
		"            letter-spacing: -0.02em;",
		"        }",
		"        @media (prefers-reduced-motion: reduce) {",
		"            *, ::before, ::after {",
		"                transition-duration: 0.01ms !important;",
		"                animation-duration: 0.01ms !important;",
		"            }",
		"        }",
		"    </style>",
		"</head>",
		'<body class="bg-neutral-950 text-neutral-100 min-h-full">',
		nav(data),
		'    <main id="content" class="mx-auto w-full max-w-[95rem] px-4 py-8">',
		content,
		"    </main>",
		'    <script src="/static/lib/alpine-components.js"></script>',
		'    <script defer src="/static/lib/alpine.min.js"></script>',
		toast(data),
		"</body>",
		"</html>",
	}, "\n")
end
