package pluginutil

import "testing"

// Test data: the real mangafire VRF tables/keys (rotates with keiyoushi
// updates — replace when the site rotation happens).
var (
	vrfK1 = "0Ec58JOY3uBzJK9m3zqIOpdlF7UFiax9DmA="
	vrfT1 = "yINlmUNho8VYJT+ibTIP+9ESiULpVEtMOoD6U6lRE0R/xwXo/Xp9NrUgC4cw/Lmo33vUyjUE40kUoEWIr/fxfNNcq2s79ShQ5NhNrFnJ4hXPwOu/SuXzIbuTQKGFvfm08E9jvCfqAtoDqvQq3dVWPQFmJjgvkISBeXY3BgANR+yVnjGbcxZ47d6kLNfZPIayTq3/YGySb1KuVZodWp/WGNAO5pfMcpaK53Hhs0allBszaMaxuouOwdxbwgxIw6YunSsXjI05Yi0j9j4eHKfSXR8Ifo/Od+8iamRfCXTyvm7NGRGYdcQ0ywcK/u6RXhrbcCm4t2eCtrDgQVecJGkQ+A=="
	vrfK2 = "AAdjb1iPY8CiDmq9H34tKTBF8a3oDQ=="
	vrfT2 = "IUFltCxD3Oc2cwCgkJffthaOg9cgPUb0LgW6H/VtfcF0kc5F25t+aWj6JH9VOhOaY0rAFdUxlDnl5BLNvwEJvQtP5qcw7vdb/K+chnbwnspSHT8mz5lqwz41TezG0hkO06FTjJZhsyNuFLDpD2ZZxQj/QIRcF90zpmQ7Byu483WsQqUE0C342HL+JXngRB6fRzxRyVTaKu83h7UYTJ0QMt6ixFh6S3F8gqkKwrGTL3jHNBsD45UnifK8+RGtishQV2K3rujLKEkiZxpr2dYcudFW4oFsDKhad3CLBvuyTqsCo4B7mL5IKQ1vXo/MOOvq1I1d8ar9X6Ttu5KF4fZgiA=="
	vrfK3 = "DELOJgPsVaCcblDtTGMdHzM="
	vrfT3 = "NQHlu1/wVO5EmkwQymF810qqY2xG1k2obcas4Z9mCsPEIFl9pRIjFxbJ7ybMHbBckT5Ton85E0FOeHezbh/mjlEYpmpnlXOS8dgrqeq2KfxImTh1YK9y0PeMNhzA1OQzSY9brYOJq/l2QnE/hwOeZIhPixVSKIUlDb5vLcH6RWKxkIEMuP0bDwIqQ71AJJaEaMJL7A6YtyIwoRT+L5v4aZzodN/0+3nOGsfblFjgxSfPzVDjNFeNl5P26+kEC/8AHgdrpAbt3hHz3HrRN1Y6e+JHgF7ncFWnoF0y3THL1S71WgWGCa6KtSzTCCG58n68nTyj2T3Sshk7utqCtMi/ZQ=="
)

func vrfTestStages(t *testing.T) []VRFStage {
	t.Helper()
	st, err := VRFStagesB64([]VRFStageB64{
		{IV: 0x5A, Key: vrfK1, Tbl: vrfT1},
		{IV: 0x35, Key: vrfK2, Tbl: vrfT2},
		{IV: 0xBA, Key: vrfK3, Tbl: vrfT3},
	})
	if err != nil {
		t.Fatalf("decode stages: %v", err)
	}
	return st
}

// Golden vectors generated by the live JS plugin implementation
// (examples/plugins/js/mangafire/main.js) — byte-for-byte parity required.
func TestVRFSignGolden(t *testing.T) {
	st := vrfTestStages(t)
	cases := []struct {
		name    string
		apiPath string
		params  map[string]string
		want    string
	}{
		{"empty", "/titles", map[string]string{}, "8sK3xtqdFQ"},
		{"one", "/manga", map[string]string{"limit": "50"}, "8qEkqsbjQMrPN82PZEAP"},
		{"sorted", "/titles", map[string]string{"keyword": "naruto", "limit": "50", "page": "1"}, "8sK3xtqdFZfetBhus6bRAjHyEL3W3G_rnxgOXpPB0_i8tncqWLs"},
		{"apiStrip", "/api/titles", map[string]string{"page": "2"}, "8sK3xtqdFZfnfxImVdE"},
		{"utf8", "/search", map[string]string{"q": "はじめの一歩"}, "8rmP5f_9tOdgg-j3a5w_WQte2iUPEj6pvQYSPw"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := VRFSign(tc.apiPath, tc.params, st)
			if got != tc.want {
				t.Errorf("VRFSign(%q, %v) = %q, want %q", tc.apiPath, tc.params, got, tc.want)
			}
		})
	}
}

func TestVRFStagesB64Error(t *testing.T) {
	if _, err := VRFStagesB64([]VRFStageB64{{Key: "!!!", Tbl: "!!!"}}); err == nil {
		t.Fatal("expected error for invalid base64")
	}
}
