//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var AltTitles = newAltTitlesTable("", "alt_titles", "")

type altTitlesTable struct {
	sqlite.Table

	// Columns
	ID         sqlite.ColumnInteger
	MangaRowID sqlite.ColumnString
	Title      sqlite.ColumnString
	Source     sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type AltTitlesTable struct {
	altTitlesTable

	EXCLUDED altTitlesTable
}

// AS creates new AltTitlesTable with assigned alias
func (a AltTitlesTable) AS(alias string) *AltTitlesTable {
	return newAltTitlesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AltTitlesTable with assigned schema name
func (a AltTitlesTable) FromSchema(schemaName string) *AltTitlesTable {
	return newAltTitlesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AltTitlesTable with assigned table prefix
func (a AltTitlesTable) WithPrefix(prefix string) *AltTitlesTable {
	return newAltTitlesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AltTitlesTable with assigned table suffix
func (a AltTitlesTable) WithSuffix(suffix string) *AltTitlesTable {
	return newAltTitlesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAltTitlesTable(schemaName, tableName, alias string) *AltTitlesTable {
	return &AltTitlesTable{
		altTitlesTable: newAltTitlesTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newAltTitlesTableImpl("", "excluded", ""),
	}
}

func newAltTitlesTableImpl(schemaName, tableName, alias string) altTitlesTable {
	var (
		IDColumn         = sqlite.IntegerColumn("id")
		MangaRowIDColumn = sqlite.StringColumn("manga_row_id")
		TitleColumn      = sqlite.StringColumn("title")
		SourceColumn     = sqlite.StringColumn("source")
		allColumns       = sqlite.ColumnList{IDColumn, MangaRowIDColumn, TitleColumn, SourceColumn}
		mutableColumns   = sqlite.ColumnList{MangaRowIDColumn, TitleColumn, SourceColumn}
		defaultColumns   = sqlite.ColumnList{}
	)

	return altTitlesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		MangaRowID: MangaRowIDColumn,
		Title:      TitleColumn,
		Source:     SourceColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
