//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Chapters = newChaptersTable("", "chapters", "")

type chaptersTable struct {
	sqlite.Table

	// Columns
	ID              sqlite.ColumnString
	MangaID         sqlite.ColumnString
	SourceChapterID sqlite.ColumnString
	Title           sqlite.ColumnString
	ChapterNum      sqlite.ColumnFloat
	VolumeNum       sqlite.ColumnFloat
	IsRead          sqlite.ColumnInteger
	LastPageRead    sqlite.ColumnInteger
	DownloadStatus  sqlite.ColumnString
	FetchedAt       sqlite.ColumnTimestamp
	TotalPages      sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ChaptersTable struct {
	chaptersTable

	EXCLUDED chaptersTable
}

// AS creates new ChaptersTable with assigned alias
func (a ChaptersTable) AS(alias string) *ChaptersTable {
	return newChaptersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ChaptersTable with assigned schema name
func (a ChaptersTable) FromSchema(schemaName string) *ChaptersTable {
	return newChaptersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ChaptersTable with assigned table prefix
func (a ChaptersTable) WithPrefix(prefix string) *ChaptersTable {
	return newChaptersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ChaptersTable with assigned table suffix
func (a ChaptersTable) WithSuffix(suffix string) *ChaptersTable {
	return newChaptersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newChaptersTable(schemaName, tableName, alias string) *ChaptersTable {
	return &ChaptersTable{
		chaptersTable: newChaptersTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newChaptersTableImpl("", "excluded", ""),
	}
}

func newChaptersTableImpl(schemaName, tableName, alias string) chaptersTable {
	var (
		IDColumn              = sqlite.StringColumn("id")
		MangaIDColumn         = sqlite.StringColumn("manga_id")
		SourceChapterIDColumn = sqlite.StringColumn("source_chapter_id")
		TitleColumn           = sqlite.StringColumn("title")
		ChapterNumColumn      = sqlite.FloatColumn("chapter_num")
		VolumeNumColumn       = sqlite.FloatColumn("volume_num")
		IsReadColumn          = sqlite.IntegerColumn("is_read")
		LastPageReadColumn    = sqlite.IntegerColumn("last_page_read")
		DownloadStatusColumn  = sqlite.StringColumn("download_status")
		FetchedAtColumn       = sqlite.TimestampColumn("fetched_at")
		TotalPagesColumn      = sqlite.IntegerColumn("total_pages")
		allColumns            = sqlite.ColumnList{IDColumn, MangaIDColumn, SourceChapterIDColumn, TitleColumn, ChapterNumColumn, VolumeNumColumn, IsReadColumn, LastPageReadColumn, DownloadStatusColumn, FetchedAtColumn, TotalPagesColumn}
		mutableColumns        = sqlite.ColumnList{MangaIDColumn, SourceChapterIDColumn, TitleColumn, ChapterNumColumn, VolumeNumColumn, IsReadColumn, LastPageReadColumn, DownloadStatusColumn, FetchedAtColumn, TotalPagesColumn}
		defaultColumns        = sqlite.ColumnList{IsReadColumn, LastPageReadColumn, DownloadStatusColumn, FetchedAtColumn, TotalPagesColumn}
	)

	return chaptersTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		MangaID:         MangaIDColumn,
		SourceChapterID: SourceChapterIDColumn,
		Title:           TitleColumn,
		ChapterNum:      ChapterNumColumn,
		VolumeNum:       VolumeNumColumn,
		IsRead:          IsReadColumn,
		LastPageRead:    LastPageReadColumn,
		DownloadStatus:  DownloadStatusColumn,
		FetchedAt:       FetchedAtColumn,
		TotalPages:      TotalPagesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
