//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFts = newLibraryFtsTable("", "library_fts", "")

type libraryFtsTable struct {
	sqlite.Table

	// Columns
	Title      sqlite.ColumnString
	Alt        sqlite.ColumnString
	PluginID   sqlite.ColumnString
	MangaRowID sqlite.ColumnString
	LibraryFts sqlite.ColumnString
	Rank       sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsTable struct {
	libraryFtsTable

	EXCLUDED libraryFtsTable
}

// AS creates new LibraryFtsTable with assigned alias
func (a LibraryFtsTable) AS(alias string) *LibraryFtsTable {
	return newLibraryFtsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsTable with assigned schema name
func (a LibraryFtsTable) FromSchema(schemaName string) *LibraryFtsTable {
	return newLibraryFtsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsTable with assigned table prefix
func (a LibraryFtsTable) WithPrefix(prefix string) *LibraryFtsTable {
	return newLibraryFtsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsTable with assigned table suffix
func (a LibraryFtsTable) WithSuffix(suffix string) *LibraryFtsTable {
	return newLibraryFtsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsTable(schemaName, tableName, alias string) *LibraryFtsTable {
	return &LibraryFtsTable{
		libraryFtsTable: newLibraryFtsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newLibraryFtsTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsTableImpl(schemaName, tableName, alias string) libraryFtsTable {
	var (
		TitleColumn      = sqlite.StringColumn("title")
		AltColumn        = sqlite.StringColumn("alt")
		PluginIDColumn   = sqlite.StringColumn("plugin_id")
		MangaRowIDColumn = sqlite.StringColumn("manga_row_id")
		LibraryFtsColumn = sqlite.StringColumn("library_fts")
		RankColumn       = sqlite.StringColumn("rank")
		allColumns       = sqlite.ColumnList{TitleColumn, AltColumn, PluginIDColumn, MangaRowIDColumn, LibraryFtsColumn, RankColumn}
		mutableColumns   = sqlite.ColumnList{TitleColumn, AltColumn, PluginIDColumn, MangaRowIDColumn, LibraryFtsColumn, RankColumn}
		defaultColumns   = sqlite.ColumnList{}
	)

	return libraryFtsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Title:      TitleColumn,
		Alt:        AltColumn,
		PluginID:   PluginIDColumn,
		MangaRowID: MangaRowIDColumn,
		LibraryFts: LibraryFtsColumn,
		Rank:       RankColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
