//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFtsConfig = newLibraryFtsConfigTable("", "library_fts_config", "")

type libraryFtsConfigTable struct {
	sqlite.Table

	// Columns
	K sqlite.ColumnString
	V sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsConfigTable struct {
	libraryFtsConfigTable

	EXCLUDED libraryFtsConfigTable
}

// AS creates new LibraryFtsConfigTable with assigned alias
func (a LibraryFtsConfigTable) AS(alias string) *LibraryFtsConfigTable {
	return newLibraryFtsConfigTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsConfigTable with assigned schema name
func (a LibraryFtsConfigTable) FromSchema(schemaName string) *LibraryFtsConfigTable {
	return newLibraryFtsConfigTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsConfigTable with assigned table prefix
func (a LibraryFtsConfigTable) WithPrefix(prefix string) *LibraryFtsConfigTable {
	return newLibraryFtsConfigTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsConfigTable with assigned table suffix
func (a LibraryFtsConfigTable) WithSuffix(suffix string) *LibraryFtsConfigTable {
	return newLibraryFtsConfigTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsConfigTable(schemaName, tableName, alias string) *LibraryFtsConfigTable {
	return &LibraryFtsConfigTable{
		libraryFtsConfigTable: newLibraryFtsConfigTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newLibraryFtsConfigTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsConfigTableImpl(schemaName, tableName, alias string) libraryFtsConfigTable {
	var (
		KColumn        = sqlite.StringColumn("k")
		VColumn        = sqlite.StringColumn("v")
		allColumns     = sqlite.ColumnList{KColumn, VColumn}
		mutableColumns = sqlite.ColumnList{VColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return libraryFtsConfigTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		K: KColumn,
		V: VColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
