//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFtsContent = newLibraryFtsContentTable("", "library_fts_content", "")

type libraryFtsContentTable struct {
	sqlite.Table

	// Columns
	ID sqlite.ColumnInteger
	C0 sqlite.ColumnString
	C1 sqlite.ColumnString
	C2 sqlite.ColumnString
	C3 sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsContentTable struct {
	libraryFtsContentTable

	EXCLUDED libraryFtsContentTable
}

// AS creates new LibraryFtsContentTable with assigned alias
func (a LibraryFtsContentTable) AS(alias string) *LibraryFtsContentTable {
	return newLibraryFtsContentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsContentTable with assigned schema name
func (a LibraryFtsContentTable) FromSchema(schemaName string) *LibraryFtsContentTable {
	return newLibraryFtsContentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsContentTable with assigned table prefix
func (a LibraryFtsContentTable) WithPrefix(prefix string) *LibraryFtsContentTable {
	return newLibraryFtsContentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsContentTable with assigned table suffix
func (a LibraryFtsContentTable) WithSuffix(suffix string) *LibraryFtsContentTable {
	return newLibraryFtsContentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsContentTable(schemaName, tableName, alias string) *LibraryFtsContentTable {
	return &LibraryFtsContentTable{
		libraryFtsContentTable: newLibraryFtsContentTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newLibraryFtsContentTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsContentTableImpl(schemaName, tableName, alias string) libraryFtsContentTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		C0Column       = sqlite.StringColumn("c0")
		C1Column       = sqlite.StringColumn("c1")
		C2Column       = sqlite.StringColumn("c2")
		C3Column       = sqlite.StringColumn("c3")
		allColumns     = sqlite.ColumnList{IDColumn, C0Column, C1Column, C2Column, C3Column}
		mutableColumns = sqlite.ColumnList{C0Column, C1Column, C2Column, C3Column}
		defaultColumns = sqlite.ColumnList{}
	)

	return libraryFtsContentTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,
		C0: C0Column,
		C1: C1Column,
		C2: C2Column,
		C3: C3Column,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
