//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFtsDocsize = newLibraryFtsDocsizeTable("", "library_fts_docsize", "")

type libraryFtsDocsizeTable struct {
	sqlite.Table

	// Columns
	ID sqlite.ColumnInteger
	Sz sqlite.ColumnBlob

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsDocsizeTable struct {
	libraryFtsDocsizeTable

	EXCLUDED libraryFtsDocsizeTable
}

// AS creates new LibraryFtsDocsizeTable with assigned alias
func (a LibraryFtsDocsizeTable) AS(alias string) *LibraryFtsDocsizeTable {
	return newLibraryFtsDocsizeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsDocsizeTable with assigned schema name
func (a LibraryFtsDocsizeTable) FromSchema(schemaName string) *LibraryFtsDocsizeTable {
	return newLibraryFtsDocsizeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsDocsizeTable with assigned table prefix
func (a LibraryFtsDocsizeTable) WithPrefix(prefix string) *LibraryFtsDocsizeTable {
	return newLibraryFtsDocsizeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsDocsizeTable with assigned table suffix
func (a LibraryFtsDocsizeTable) WithSuffix(suffix string) *LibraryFtsDocsizeTable {
	return newLibraryFtsDocsizeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsDocsizeTable(schemaName, tableName, alias string) *LibraryFtsDocsizeTable {
	return &LibraryFtsDocsizeTable{
		libraryFtsDocsizeTable: newLibraryFtsDocsizeTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newLibraryFtsDocsizeTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsDocsizeTableImpl(schemaName, tableName, alias string) libraryFtsDocsizeTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		SzColumn       = sqlite.BlobColumn("sz")
		allColumns     = sqlite.ColumnList{IDColumn, SzColumn}
		mutableColumns = sqlite.ColumnList{SzColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return libraryFtsDocsizeTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID: IDColumn,
		Sz: SzColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
