//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFtsIdx = newLibraryFtsIdxTable("", "library_fts_idx", "")

type libraryFtsIdxTable struct {
	sqlite.Table

	// Columns
	Segid sqlite.ColumnString
	Term  sqlite.ColumnString
	Pgno  sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsIdxTable struct {
	libraryFtsIdxTable

	EXCLUDED libraryFtsIdxTable
}

// AS creates new LibraryFtsIdxTable with assigned alias
func (a LibraryFtsIdxTable) AS(alias string) *LibraryFtsIdxTable {
	return newLibraryFtsIdxTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsIdxTable with assigned schema name
func (a LibraryFtsIdxTable) FromSchema(schemaName string) *LibraryFtsIdxTable {
	return newLibraryFtsIdxTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsIdxTable with assigned table prefix
func (a LibraryFtsIdxTable) WithPrefix(prefix string) *LibraryFtsIdxTable {
	return newLibraryFtsIdxTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsIdxTable with assigned table suffix
func (a LibraryFtsIdxTable) WithSuffix(suffix string) *LibraryFtsIdxTable {
	return newLibraryFtsIdxTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsIdxTable(schemaName, tableName, alias string) *LibraryFtsIdxTable {
	return &LibraryFtsIdxTable{
		libraryFtsIdxTable: newLibraryFtsIdxTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newLibraryFtsIdxTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsIdxTableImpl(schemaName, tableName, alias string) libraryFtsIdxTable {
	var (
		SegidColumn    = sqlite.StringColumn("segid")
		TermColumn     = sqlite.StringColumn("term")
		PgnoColumn     = sqlite.StringColumn("pgno")
		allColumns     = sqlite.ColumnList{SegidColumn, TermColumn, PgnoColumn}
		mutableColumns = sqlite.ColumnList{PgnoColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return libraryFtsIdxTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Segid: SegidColumn,
		Term:  TermColumn,
		Pgno:  PgnoColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
