//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var LibraryFtsData = newLibraryFtsDataTable("", "library_fts_data", "")

type libraryFtsDataTable struct {
	sqlite.Table

	// Columns
	ID    sqlite.ColumnInteger
	Block sqlite.ColumnBlob

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type LibraryFtsDataTable struct {
	libraryFtsDataTable

	EXCLUDED libraryFtsDataTable
}

// AS creates new LibraryFtsDataTable with assigned alias
func (a LibraryFtsDataTable) AS(alias string) *LibraryFtsDataTable {
	return newLibraryFtsDataTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LibraryFtsDataTable with assigned schema name
func (a LibraryFtsDataTable) FromSchema(schemaName string) *LibraryFtsDataTable {
	return newLibraryFtsDataTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LibraryFtsDataTable with assigned table prefix
func (a LibraryFtsDataTable) WithPrefix(prefix string) *LibraryFtsDataTable {
	return newLibraryFtsDataTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LibraryFtsDataTable with assigned table suffix
func (a LibraryFtsDataTable) WithSuffix(suffix string) *LibraryFtsDataTable {
	return newLibraryFtsDataTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLibraryFtsDataTable(schemaName, tableName, alias string) *LibraryFtsDataTable {
	return &LibraryFtsDataTable{
		libraryFtsDataTable: newLibraryFtsDataTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newLibraryFtsDataTableImpl("", "excluded", ""),
	}
}

func newLibraryFtsDataTableImpl(schemaName, tableName, alias string) libraryFtsDataTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		BlockColumn    = sqlite.BlobColumn("block")
		allColumns     = sqlite.ColumnList{IDColumn, BlockColumn}
		mutableColumns = sqlite.ColumnList{BlockColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return libraryFtsDataTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:    IDColumn,
		Block: BlockColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
