//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Mangas = newMangasTable("", "mangas", "")

type mangasTable struct {
	sqlite.Table

	// Columns
	ID            sqlite.ColumnString
	PluginID      sqlite.ColumnString
	SourceMangaID sqlite.ColumnString
	Title         sqlite.ColumnString
	CoverURL      sqlite.ColumnString
	Description   sqlite.ColumnString
	Status        sqlite.ColumnString
	InLibrary     sqlite.ColumnInteger
	CreatedAt     sqlite.ColumnTimestamp
	UpdatedAt     sqlite.ColumnTimestamp
	NewSince      sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MangasTable struct {
	mangasTable

	EXCLUDED mangasTable
}

// AS creates new MangasTable with assigned alias
func (a MangasTable) AS(alias string) *MangasTable {
	return newMangasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MangasTable with assigned schema name
func (a MangasTable) FromSchema(schemaName string) *MangasTable {
	return newMangasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MangasTable with assigned table prefix
func (a MangasTable) WithPrefix(prefix string) *MangasTable {
	return newMangasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MangasTable with assigned table suffix
func (a MangasTable) WithSuffix(suffix string) *MangasTable {
	return newMangasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMangasTable(schemaName, tableName, alias string) *MangasTable {
	return &MangasTable{
		mangasTable: newMangasTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newMangasTableImpl("", "excluded", ""),
	}
}

func newMangasTableImpl(schemaName, tableName, alias string) mangasTable {
	var (
		IDColumn            = sqlite.StringColumn("id")
		PluginIDColumn      = sqlite.StringColumn("plugin_id")
		SourceMangaIDColumn = sqlite.StringColumn("source_manga_id")
		TitleColumn         = sqlite.StringColumn("title")
		CoverURLColumn      = sqlite.StringColumn("cover_url")
		DescriptionColumn   = sqlite.StringColumn("description")
		StatusColumn        = sqlite.StringColumn("status")
		InLibraryColumn     = sqlite.IntegerColumn("in_library")
		CreatedAtColumn     = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn     = sqlite.TimestampColumn("updated_at")
		NewSinceColumn      = sqlite.TimestampColumn("new_since")
		allColumns          = sqlite.ColumnList{IDColumn, PluginIDColumn, SourceMangaIDColumn, TitleColumn, CoverURLColumn, DescriptionColumn, StatusColumn, InLibraryColumn, CreatedAtColumn, UpdatedAtColumn, NewSinceColumn}
		mutableColumns      = sqlite.ColumnList{PluginIDColumn, SourceMangaIDColumn, TitleColumn, CoverURLColumn, DescriptionColumn, StatusColumn, InLibraryColumn, CreatedAtColumn, UpdatedAtColumn, NewSinceColumn}
		defaultColumns      = sqlite.ColumnList{InLibraryColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return mangasTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		PluginID:      PluginIDColumn,
		SourceMangaID: SourceMangaIDColumn,
		Title:         TitleColumn,
		CoverURL:      CoverURLColumn,
		Description:   DescriptionColumn,
		Status:        StatusColumn,
		InLibrary:     InLibraryColumn,
		CreatedAt:     CreatedAtColumn,
		UpdatedAt:     UpdatedAtColumn,
		NewSince:      NewSinceColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
