//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Plugins = newPluginsTable("", "plugins", "")

type pluginsTable struct {
	sqlite.Table

	// Columns
	ID       sqlite.ColumnString
	Name     sqlite.ColumnString
	Version  sqlite.ColumnString
	WasmPath sqlite.ColumnString
	IsActive sqlite.ColumnInteger
	IconURL  sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type PluginsTable struct {
	pluginsTable

	EXCLUDED pluginsTable
}

// AS creates new PluginsTable with assigned alias
func (a PluginsTable) AS(alias string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PluginsTable with assigned schema name
func (a PluginsTable) FromSchema(schemaName string) *PluginsTable {
	return newPluginsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PluginsTable with assigned table prefix
func (a PluginsTable) WithPrefix(prefix string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PluginsTable with assigned table suffix
func (a PluginsTable) WithSuffix(suffix string) *PluginsTable {
	return newPluginsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPluginsTable(schemaName, tableName, alias string) *PluginsTable {
	return &PluginsTable{
		pluginsTable: newPluginsTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newPluginsTableImpl("", "excluded", ""),
	}
}

func newPluginsTableImpl(schemaName, tableName, alias string) pluginsTable {
	var (
		IDColumn       = sqlite.StringColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		VersionColumn  = sqlite.StringColumn("version")
		WasmPathColumn = sqlite.StringColumn("wasm_path")
		IsActiveColumn = sqlite.IntegerColumn("is_active")
		IconURLColumn  = sqlite.StringColumn("icon_url")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn, VersionColumn, WasmPathColumn, IsActiveColumn, IconURLColumn}
		mutableColumns = sqlite.ColumnList{NameColumn, VersionColumn, WasmPathColumn, IsActiveColumn, IconURLColumn}
		defaultColumns = sqlite.ColumnList{IsActiveColumn}
	)

	return pluginsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		Name:     NameColumn,
		Version:  VersionColumn,
		WasmPath: WasmPathColumn,
		IsActive: IsActiveColumn,
		IconURL:  IconURLColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
