//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var PluginVerify = newPluginVerifyTable("", "plugin_verify", "")

type pluginVerifyTable struct {
	sqlite.Table

	// Columns
	PluginID  sqlite.ColumnString
	VerifyURL sqlite.ColumnString
	Cookies   sqlite.ColumnString
	UserAgent sqlite.ColumnString
	UpdatedAt sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type PluginVerifyTable struct {
	pluginVerifyTable

	EXCLUDED pluginVerifyTable
}

// AS creates new PluginVerifyTable with assigned alias
func (a PluginVerifyTable) AS(alias string) *PluginVerifyTable {
	return newPluginVerifyTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PluginVerifyTable with assigned schema name
func (a PluginVerifyTable) FromSchema(schemaName string) *PluginVerifyTable {
	return newPluginVerifyTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PluginVerifyTable with assigned table prefix
func (a PluginVerifyTable) WithPrefix(prefix string) *PluginVerifyTable {
	return newPluginVerifyTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PluginVerifyTable with assigned table suffix
func (a PluginVerifyTable) WithSuffix(suffix string) *PluginVerifyTable {
	return newPluginVerifyTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPluginVerifyTable(schemaName, tableName, alias string) *PluginVerifyTable {
	return &PluginVerifyTable{
		pluginVerifyTable: newPluginVerifyTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newPluginVerifyTableImpl("", "excluded", ""),
	}
}

func newPluginVerifyTableImpl(schemaName, tableName, alias string) pluginVerifyTable {
	var (
		PluginIDColumn  = sqlite.StringColumn("plugin_id")
		VerifyURLColumn = sqlite.StringColumn("verify_url")
		CookiesColumn   = sqlite.StringColumn("cookies")
		UserAgentColumn = sqlite.StringColumn("user_agent")
		UpdatedAtColumn = sqlite.IntegerColumn("updated_at")
		allColumns      = sqlite.ColumnList{PluginIDColumn, VerifyURLColumn, CookiesColumn, UserAgentColumn, UpdatedAtColumn}
		mutableColumns  = sqlite.ColumnList{VerifyURLColumn, CookiesColumn, UserAgentColumn, UpdatedAtColumn}
		defaultColumns  = sqlite.ColumnList{VerifyURLColumn, CookiesColumn, UserAgentColumn, UpdatedAtColumn}
	)

	return pluginVerifyTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		PluginID:  PluginIDColumn,
		VerifyURL: VerifyURLColumn,
		Cookies:   CookiesColumn,
		UserAgent: UserAgentColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
