//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ReadHistory = newReadHistoryTable("", "read_history", "")

type readHistoryTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	ChapterID sqlite.ColumnString
	PageNum   sqlite.ColumnInteger
	ReadAt    sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ReadHistoryTable struct {
	readHistoryTable

	EXCLUDED readHistoryTable
}

// AS creates new ReadHistoryTable with assigned alias
func (a ReadHistoryTable) AS(alias string) *ReadHistoryTable {
	return newReadHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ReadHistoryTable with assigned schema name
func (a ReadHistoryTable) FromSchema(schemaName string) *ReadHistoryTable {
	return newReadHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ReadHistoryTable with assigned table prefix
func (a ReadHistoryTable) WithPrefix(prefix string) *ReadHistoryTable {
	return newReadHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ReadHistoryTable with assigned table suffix
func (a ReadHistoryTable) WithSuffix(suffix string) *ReadHistoryTable {
	return newReadHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newReadHistoryTable(schemaName, tableName, alias string) *ReadHistoryTable {
	return &ReadHistoryTable{
		readHistoryTable: newReadHistoryTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newReadHistoryTableImpl("", "excluded", ""),
	}
}

func newReadHistoryTableImpl(schemaName, tableName, alias string) readHistoryTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		ChapterIDColumn = sqlite.StringColumn("chapter_id")
		PageNumColumn   = sqlite.IntegerColumn("page_num")
		ReadAtColumn    = sqlite.TimestampColumn("read_at")
		allColumns      = sqlite.ColumnList{IDColumn, ChapterIDColumn, PageNumColumn, ReadAtColumn}
		mutableColumns  = sqlite.ColumnList{ChapterIDColumn, PageNumColumn, ReadAtColumn}
		defaultColumns  = sqlite.ColumnList{ReadAtColumn}
	)

	return readHistoryTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ChapterID: ChapterIDColumn,
		PageNum:   PageNumColumn,
		ReadAt:    ReadAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
