//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Chapters struct {
	ID              *string `sql:"primary_key"`
	MangaID         string
	SourceChapterID string
	Title           string
	ChapterNum      float64
	VolumeNum       *float64
	IsRead          *int64
	LastPageRead    *int64
	DownloadStatus  *string
	FetchedAt       *time.Time
}
