//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LibraryFts struct {
	Title      *string
	Alt        *string
	PluginID   *string
	MangaRowID *string
	LibraryFts *string
	Rank       *string
}
