//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type LibraryFtsContent struct {
	ID *int64 `sql:"primary_key"`
	C0 *string
	C1 *string
	C2 *string
	C3 *string
}
