//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Mangas struct {
	ID            *string `sql:"primary_key"`
	PluginID      string
	SourceMangaID string
	Title         string
	CoverURL      *string
	Description   *string
	Status        *string
	InLibrary     *int64
	CreatedAt     *time.Time
	UpdatedAt     *time.Time
	NewSince      *time.Time
	AltTitles     *string
}
