//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Plugins struct {
	ID       *string `sql:"primary_key"`
	Name     string
	Version  string
	WasmPath string
	IsActive *int64
	IconURL  *string
}
