//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PluginVerify struct {
	PluginID  *string `sql:"primary_key"`
	VerifyURL string
	Cookies   string
	UserAgent string
	UpdatedAt int64
}
